#FRIST define the version of the yaml file
version: '3'

services:
  tweet_collector: #name of the service
    build: ./tweet_collector/.
    depends_on:
      - mongodb
    env_file:
      - .env

  etl_job:
    build: ./etl_job/.
    env_file:
      - .env
    depends_on:
      - postgresdb
      - mongodb
      - tweet_collector

  postgresdb:
    image: postgres:latest
    ports:
      - 5555:5432
    env_file:
      - .env
  
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    env_file:
      - .env
  
  metabase:
    build: ./metabase/.
    volumes:
      - ./metabase/metabase-data:/metabase-data
    ports:
      - 3000:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    depends_on:
      - postgresdb
      - mongodb
      - tweet_collector
      - etl_job